### ISSUE TITLE
notify authors if their paper has been updated

### ISSUE THREAD

**Issue by marwahaha** [arxivwiki/arxivwiki#18]
Suggested by a QOSF slack user 

Perhaps they would like to contribute to discussion about their work.  However this feature might take a lot of effort to build.
* Should we contact them? (Do authors want to be contacted?)
* Should we contact them every time the page updates? 
* How do we contact them?

**Comment by Dario-Rosa85** [comment]
My suggestion would be to contact them at least once, when the first comment on the paper appears. This is because, depending on the content of the comment, the authors could be highly interested in joining the discussion. After the first notification, the author should have the chance to receive further notifications or not (the default should be no).

About the way to notify them, the email address of the corresponding author is freely available on arXiv, so the corresponding author could be contacted through that email.

**Comment by marwahaha** [comment]
To view the email, I have to log in, then go through a captcha. I think it is designed to restrict programmatic access.

I am transitioning towards having authors write more of the content if possible. So I don't think I will build this in.
